application: angulardirectives
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /index.html
  static_files: index.html
  upload: index.html

- url: /scripts
  static_dir: scripts

#- url: .*
#  script: main.php
